### ISSUE TITLE
webapp azure

### ISSUE THREAD

**Issue by marcelloexp386** [horihiro/azure-functions-python-opencv-example#2] opened 2019-12-13 17:05 UTC
Dear Horihiro, I am trying to adapt your solution to a webapp flask+python that I would like to deploy on Azure. It works wonderfully on the localhost but it fails when on Azure. Looking at the log, the problem is: "ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"

It would be extremely kind and appreciated, if you could give me some hints on how to solve the problem.

Yours
Marcello Esposito

Here the log:

"[ERROR] Exception in worker process
2019-12-13T16:47:03.852654698Z Traceback (most recent call last):
2019-12-13T16:47:03.852665299Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-12-13T16:47:03.852685799Z     worker.init_process()
2019-12-13T16:47:03.852694900Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-12-13T16:47:03.852703600Z     self.load_wsgi()
2019-12-13T16:47:03.852711300Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-12-13T16:47:03.852719300Z     self.wsgi = self.app.wsgi()
2019-12-13T16:47:03.852727000Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-12-13T16:47:03.852735601Z     self.callable = self.load()
2019-12-13T16:47:03.852743401Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-12-13T16:47:03.852751401Z     return self.load_wsgiapp()
2019-12-13T16:47:03.852759101Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-12-13T16:47:03.852767202Z     return util.import_app(self.app_uri)
2019-12-13T16:47:03.852774902Z   File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2019-12-13T16:47:03.852782902Z     __import__(module)
2019-12-13T16:47:03.852791202Z   File "/home/site/wwwroot/app.py", line 4, in 
2019-12-13T16:47:03.852799803Z     import cv2
2019-12-13T16:47:03.852807403Z   File "/antenv/lib/python3.7/site-packages/cv2/__init__.py", line 3, in 
2019-12-13T16:47:03.852815503Z     from .cv2 import *
2019-12-13T16:47:03.852822903Z ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by horihiro** [comment] 2019-12-13 23:35
Hi @marcelloexp386 

You want to use opencv with python stack on App Service on Linux, not Function App, right?

App Service can use custom startup script which Function App cannot do it.

So I think it's more appropriate to use custom startup script which includes `apt update && apt install libglib2.0-0 -y` and flask startup command, on Startup Command.
https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-04

**Comment by horihiro** [comment] 2019-12-13 23:39
If you want to use this repo's solution on App Service on Linux, could you please show reproducable code and your file structure?

**Comment by marcelloexp386** [comment] 2019-12-14 10:45
Hi Horihiro,
the simple app that I am attaching transforms an uploaded  "color" picture in a "bw" picture. The input and the output files are stored in "input" and "output" sub-directories. My operating system is Windows10, my Python is 3. Anyway, you can find in requirements.txt all the info
[opencv_azure.zip](https://github.com/horihiro/azure-functions-python-opencv-example/files/3963708/opencv_azure.zip)

**Comment by horihiro** [comment] 2019-12-14 11:49
I cannot find `libglib-2.0.so.0` and `libgthread-2.0.so.0` in your project.

Did you try this in order to get them?
https://github.com/horihiro/azure-functions-python-opencv-example/tree/master/utils

And I recommend installing `libglib2.0-0` in startup script for WebApp than this repo's solution.

**Comment by marcelloexp386** [comment] 2019-12-14 12:34
I added the following startup.txt but still no solution:

sudo apt-get update && sudo apt-get install -y libglib2.0-0
gunicorn --bind=0.0.0.0 --timeout 600 app:app

**Comment by horihiro** [comment] 2019-12-14 13:45
You need to do a few things in order to make this app work

1. Edit modules in `requirements.txt` from `opencv-python` to `opencv-python-headless`
`opencv-python-headless` has less dependencies than `opencv-python`

1. Upload start.sh to your WebApp (ex. /home/start.sh) via ftp etc.
    ```sh
    #!/bin/bash
    apt update && apt install -y libglib2.0-0
    gunicorn --bind=0.0.0.0 --timeout 600 app:app
    ```
1. Set `sh /PATH/TO/start.sh` to Startup Command
![image](https://user-images.githubusercontent.com/4566555/70849494-7134dd00-1ec2-11ea-8cf1-c8639da042ec.png)

Then, `libglib2.0-0` is installed on startup and you will be able to see the following page without any errors.
![image](https://user-images.githubusercontent.com/4566555/70849566-747c9880-1ec3-11ea-89c6-7e21653a3528.png)

**Comment by horihiro** [comment] 2019-12-17 09:05
can I close this issue because this is not related ri this repo?

**Comment by marcelloexp386** [comment] 2019-12-17 09:11
Yes and thanks for the help. Unfortunately, I was unable to fix it. I then decided to use Pillow instead of OpenCV and the webapp is now working both on local and on Azure.

**Closed as completed** 2019-12-17 22:02 UTC
